name: Quran
description: A Quran App focused on recitations.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  quran: ^1.2.2
  record: ^4.4.4
  audioplayers: ^4.1.0
  hadith: ^1.0.0
  firebase_core: ^2.15.0
  # firebase_analytics: ^10.4.4
  # firebase_app_check: ^0.1.5+1
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  # cloud_functions: ^4.3.4
  firebase_storage: ^11.2.5
  # firebase_crashlytics: ^3.3.4
  # firebase_dynamic_links: ^5.3.4
  # firebase_in_app_messaging: ^0.7.3+4
  # firebase_app_installations: ^0.2.3+4
  # firebase_ml_model_downloader: ^0.2.3+4
  # firebase_performance: ^0.9.2+4
  firebase_database: ^10.2.4
  camera: ^0.10.5+2
  video_player: ^2.7.0
  flutter_login: ^4.2.0
  material_text_fields: ^1.0.3
  font_awesome_flutter: ^10.5.0
  google_sign_in: ^6.1.4
  profanity_filter: ^2.0.0
  google_fonts: ^4.0.4
  sign_in_with_apple: ^5.0.0
  facebook_auth: ^0.0.3
  adhan_dart: ^1.0.8
  flutter_qiblah: ^2.2.0
  permission_handler: ^10.4.3
  timezone: ^0.9.2
  theme_provider: ^0.6.0
  url_launcher: ^6.1.12
  provider: ^6.0.5
  # firebase_remote_config: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  file_manager: ^1.0.0
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets\fonts\Amiri\Amiri-Regular.ttf

    - family: KFGQPC Uthmanic Script HAFS Regular
      fonts:
        - asset: assets\fonts\KFGQPC Uthmanic Script HAFS Regular\KFGQPC Uthmanic Script HAFS Regular.otf

    - family: PDMS Saleem
      fonts:
        - asset: assets\fonts\_PDMS_Saleem_QuranFont.ttf

    - family: Al Qalam Quran Majeed
      fonts:
        - asset: assets\fonts\Al Qalam Quran Majeed\Al Qalam Quran Majeed.ttf

flutter_launcher_icons:
  image_path_android: "assets/images/app_image.png"
  image_path_ios: "assets/images/app_image.png"
  android: true
  ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_image.png"
    background_color: "#095326 "
    theme_color: "#5EBD84 "
  windows:
    generate: true
    image_path: "assets/images/app_image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_image.png"
