// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfANGfXaGV1Td_GCOvR0tZOH4ZB1eiyA',
    appId: '1:82565754609:web:a3e4d3ffa9829d34c94350',
    messagingSenderId: '82565754609',
    projectId: 'quran-app-aa669',
    authDomain: 'quran-app-aa669.firebaseapp.com',
    storageBucket: 'quran-app-aa669.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwc88E057Vr3daJL4I-B-ufsHkYJ-uFks',
    appId: '1:82565754609:android:02eb9f56d9aef924c94350',
    messagingSenderId: '82565754609',
    projectId: 'quran-app-aa669',
    storageBucket: 'quran-app-aa669.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD85fAPDe8ODpNdyBB2WqXgWHZV5ib8P6o',
    appId: '1:82565754609:ios:7c22f16fe0807629c94350',
    messagingSenderId: '82565754609',
    projectId: 'quran-app-aa669',
    storageBucket: 'quran-app-aa669.appspot.com',
    iosClientId: '82565754609-vbf343m2g1hmdjabmkf7a0fnd54t5q85.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD85fAPDe8ODpNdyBB2WqXgWHZV5ib8P6o',
    appId: '1:82565754609:ios:9cb7035a1e20b9d6c94350',
    messagingSenderId: '82565754609',
    projectId: 'quran-app-aa669',
    storageBucket: 'quran-app-aa669.appspot.com',
    iosClientId: '82565754609-35ujmuvjqjn57nrt3uol1p935dgqnkda.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
